#!/bin/bash

echo "fetching JIRA ticket from branch name"

# Extract the jira ticket
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
TICKET_NUMBER=$(echo "$BRANCH_NAME" | grep -o "JIRA-[0-9]\+")

echo "ticket number  $TICKET_NUMBER"

# Prepend the ticket number to the commit message if it exists
if [ -n "$TICKET_NUMBER" ]; then
    sed -i.bak -e "1s/^/$TICKET_NUMBER: /" "$1"
fi